### ISSUE TITLE
Readsbased for Bioscales

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/ReadbasedAnalysis#15]
Run reads based taxonomy analysis

**Comment by aclum** [comment]
@hubin-keio please list the issues for workflow automation you were mentioning early here as dependencies.

**Comment by Michal-Babins** [comment]
Automation should be fully iterated soon. Need to test automation package. All other wf's will need to be ingested first so only ReadBasedAnalysis jobs are propagated.

**Comment by ssarrafan** [comment]
@Michal-Babins what's the status of this?  @hubin-keio are there other dependencies or blockers?

**Comment by aclum** [comment]
There has been testing but for this to be run on all the projects in bioscales we need to have all the data ingested from JGI ([JGI data for bioscales#37](https://github.com/microbiomedata/issues/issues/37) which isn't complete yet. Please move to the next sprint.

**Comment by ssarrafan** [comment]
@aclum is this still actively being worked on?  
@Michal-Babins

**Comment by aclum** [comment]
@ssarrafan  Yes, i've moved this to the next sprint already.

**Comment by aclum** [comment]
Moving to the next sprint since not all the work will be done today.

**Comment by ssarrafan** [comment]
Most of the work is done but moving to next sprint to make sure no bugs or problems appear.
