### ISSUE TITLE
update-v1

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/ReadbasedAnalysis#19]
Update WDL files to WDL version 1.0

**Comment by mflynn-lanl** [comment]
I've updated the workflow and tasks to V1. I've tested on Expanse and now I'd like to test on NERSC before issuing a pull request

**Comment by aclum** [comment]
@mflynn-lanl how did the testing of this go?

**Comment by vlilanl** [comment]
I updated the workflow and tasks to Version 1 and I have tested on Condor. The job_id is a84ac301-7342-4b31-9a3e-1004bfa035c4. Let me know if I should make a pull request

**Comment by aclum** [comment]
@vlilanl  the Gottcha2 version doesn't get correctly populated to the profiler.info file with the v1 test. This is getting populated correctly with a recently wdl v2 run

see /pscratch/sd/n/nmdcda/cromwell-executions/ReadbasedAnalysis/fc742983-2a81-49fe-9da1-75877abf2f87/call-make_info_file/execution/profiler.info.  for what this should look like.
