### ISSUE TITLE
Update databases

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/ReadbasedAnalysis#20]
Add eukaryote and fungal databases

**Comment by aclum** [comment]
@hubin-keio  please identify someone that can work on this this sprint.

**Comment by ssarrafan** [comment]
Per slack message from Bin and Alicia, I'm assigning to just Mark Flynn and adding this to the June 3rd sprint.  This is a high priority for when @mflynn-lanl is back.

**Comment by aclum** [comment]
@mflynn-lanl  do you have time to do this this week?

**Comment by mflynn-lanl** [comment]
I copied the GOTTCHA2 fungal database to a separate directory in refdata (`/global/cfs/cdirs/m3408/refdata/gottcha2_fungal`) on Perlmutter and I just successfully ran a workflow using that database. I will create a PR and move the fungal database to `/global/cfs/cdirs/m3408/refdata/gottcha2`

**Comment by aclum** [comment]
@mflynn-lanl  I approved the PR, please make a tagged release ASAP because deleting the existing databases created a breaking change so we need to get to get workflow automation updated ASAP. @mbthornton-lbl  @scanon

**Comment by aclum** [comment]
Resolved by https://github.com/microbiomedata/ReadbasedAnalysis/pull/21
