### ISSUE TITLE
review and delete old branches 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/ReadbasedAnalysis#23]
Please review and delete if possible old branches. There is some work in the develop branch to add singleM that was never merged into master.

**Comment by poeli** [comment]
I am unsure which branch we are currently using on NMDC and NMDC-EDGE. Please provide more information, and I will merge the most up-to-date docker/WDL into the master branch.

**Comment by aclum** [comment]
We've been using [v1.0.5](https://github.com/microbiomedata/ReadbasedAnalysis/releases/tag/v1.0.5), we are trying to [v1.0.6](https://github.com/microbiomedata/ReadbasedAnalysis/releases/tag/v1.0.6). EDGE is already on [v1.0.6](https://github.com/microbiomedata/ReadbasedAnalysis/releases/tag/v1.0.6), they added the fungal GOTTCHA2 database several months ago.

**Comment by ssarrafan** [comment]
Discussed at the workflows meeting today and Valerie said she's working on this so I added it to the sprint.  @vlilanl @aclum

**Comment by vlilanl** [comment]
I was able to review and clean up the branches.

The [develop](https://github.com/microbiomedata/ReadbasedAnalysis/tree/develop) branch is the branch that @poeli is working on singleM.
